-- Lua
local tb = require("trouble")

vim.keymap.set("n", "<leader>tt", function()
  tb.toggle()
end, { desc = "[T]rouble [T]oggle" })
vim.keymap.set("n", "<leader>tw", function()
  tb.toggle("workspace_diagnostics")
end, { desc = "[T]rouble [W]orkspace diagnostics" })
vim.keymap.set("n", "<leader>td", function()
  tb.toggle("document_diagnostics")
end, { desc = "[T]rouble [D]ocument diagnostics" })
vim.keymap.set("n", "<leader>tq", function()
  tb.toggle("quickfix")
end, { desc = "[T]rouble [Q]uickfix" })
vim.keymap.set("n", "<leader>tl", function()
  tb.toggle("loclist")
end, { desc = "[T]rouble [L]oclist" })
vim.keymap.set("n", "gR", function()
  tb.toggle("lsp_references")
end, { desc = "[G]o to  [R]eferences" })
