live_config_reload = true

import = [
  "~/.config/alacritty/themes/tokyonight_storm.toml",
]

[font]
size = 10.0

[font.normal]
family = "RobotoMono Nerd Font"

[scrolling]
history = 50000
multiplier = 3

[selection]
save_to_clipboard = false

[window]
decorations = "full"
dynamic_title = false
opacity = 0.95
option_as_alt = "OnlyRight"
title = "Alacritty"
