local o = vim.opt

o.autoread = true
o.autowrite = true
o.clipboard = 'unnamedplus'
o.cursorline = true
o.expandtab = true
o.ignorecase = true
o.laststatus = 2
o.list = true
o.listchars = {
  eol = '¬',
  extends = '❯',
  precedes = '❮',
  tab = '▸ ',
  trail = '⌴',
}
o.mouse = 'a'
o.number = true
o.pastetoggle = '<F2>'
o.relativenumber = true
o.scrolloff = 3
o.shiftwidth = 4
o.showmatch = true
o.signcolumn = 'yes:1'
o.smartcase = true
o.softtabstop = 4
o.splitbelow = true
o.splitright = true
o.swapfile = false
o.tabstop = 4
o.undofile = true
o.updatetime = 100
o.wrap = false
